# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/min_diffusion',
                'doc_host': 'https://enzokro.github.io',
                'git_url': 'https://github.com/enzokro/min_diffusion',
                'lib_path': 'min_diffusion'},
  'syms': {'min_diffusion.core': {'min_diffusion.core.foo': ('core.html#foo', 'min_diffusion/core.py')}}}